return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    config = function()
        local which_key = require("which-key")

        which_key.setup({
            preset = "modern",
            delay = 200,
            win = {
                border = "rounded",
            },
        })

        which_key.add({
            { "<leader>e",  desc = "Toggle File Explorer" },
            { "<leader>E",  desc = "Reveal Current File" },
            { "<leader>td", desc = "Toggle Diagnostics" },
            { "<leader>th", desc = "Toggle Inlay Hints" },
            { "<leader>tn", desc = "Toggle Line Number" },
            { "<leader>tr", desc = "Toggle Relative Number" },
            { "<leader>tw", desc = "Toggle Wrap" },
            { "<leader>m",  group = "Markdown" },
            { "<leader>mt", desc = "Toggle Markdown Render" },
            { "<leader>l",  group = "LSP/Lint/Format" },
            { "<leader>la", desc = "Code Action" },
            { "<leader>lf", desc = "Format Buffer" },
            { "<leader>lh", desc = "Signature Help" },
            { "<leader>ll", desc = "Lint Buffer" },
            { "<leader>li", desc = "Formatter Info" },
            { "<leader>lq", desc = "Diagnostics to Location List" },
            { "<leader>lQ", desc = "Diagnostics to Quickfix" },
            { "<leader>lr", desc = "Rename Symbol" },
            { "<leader>h",  group = "Git" },
            { "<leader>g",  group = "Git" },
            { "<leader>gb", desc = "Git Branches" },
            { "<leader>gd", desc = "Git Diff Hunks" },
            { "<leader>gf", desc = "Git Log Current File" },
            { "<leader>gl", desc = "LazyGit Log" },
            { "<leader>gL", desc = "Git Log Line" },
            { "<leader>gs", desc = "LazyGit" },
            { "<leader>gS", desc = "Git Stash" },
            { "<leader>hs", desc = "Stage Hunk" },
            { "<leader>hr", desc = "Reset Hunk" },
            { "<leader>hS", desc = "Stage Buffer" },
            { "<leader>hu", desc = "Undo Stage Hunk" },
            { "<leader>hp", desc = "Preview Hunk" },
            { "<leader>hb", desc = "Blame Line" },
            { "<leader>hd", desc = "Diff This" },
            { "<leader>hD", desc = "Diff Against HEAD" },
            { "<leader>f",  group = "Find" },
            { "<leader>ff", desc = "Find Files" },
            { "<leader>fg", desc = "Live Grep" },
            { "<leader>fb", desc = "Buffers" },
            { "<leader>fh", desc = "Help Tags" },
            { "<leader>fr", desc = "Recent Files" },
            { "<leader>fw", desc = "Grep Word/Selection", mode = { "n", "x" } },
            { "<leader>fd", desc = "Workspace Diagnostics" },
            { "<leader>fD", desc = "Buffer Diagnostics" },
            { "<leader>fs", desc = "Document Symbols" },
            { "<leader>fS", desc = "Workspace Symbols" },
            { "<leader>fp", desc = "Find package.json" },
            { "<leader>fR", desc = "Resume Picker" },
            { "<leader>ft", desc = "Find Todos" },
            { "<leader>x",  group = "Trouble/Diagnostics" },
            { "<leader>xx", desc = "Diagnostics" },
            { "<leader>xX", desc = "Buffer Diagnostics" },
            { "<leader>xs", desc = "Symbols" },
            { "<leader>xl", desc = "LSP Definitions/References" },
            { "<leader>xL", desc = "Location List" },
            { "<leader>xQ", desc = "Quickfix List" },
            { "<leader>xt", desc = "Todo Trouble" },
            { "<leader>d",  group = "Debug" },
            { "<leader>db", desc = "Toggle Breakpoint" },
            { "<leader>dB", desc = "Conditional Breakpoint" },
            { "<leader>dc", desc = "Continue" },
            { "<leader>di", desc = "Step Into" },
            { "<leader>do", desc = "Step Over" },
            { "<leader>dO", desc = "Step Out" },
            { "<leader>dr", desc = "Toggle REPL" },
            { "<leader>dl", desc = "Run Last" },
            { "<leader>dt", desc = "Terminate" },
            { "<leader>du", desc = "Toggle Debug UI" },
            { "<leader>j",  group = "Java" },
            { "<leader>jo", desc = "Organize Imports" },
            { "<leader>jv", desc = "Extract Variable", mode = { "n", "x" } },
            { "<leader>jm", desc = "Extract Method", mode = "x" },
            { "<leader>jt", desc = "Test Nearest Method" },
            { "<leader>jT", desc = "Test Class" },
            { "<leader>ju", desc = "Update Project Config" },
            { "<leader>jr", desc = "Restart JDTLS" },
            { "<leader>F",  group = "Flutter" },
            { "<leader>Fr", desc = "Flutter Run" },
            { "<leader>Fd", desc = "Flutter Debug" },
            { "<leader>Fq", desc = "Flutter Quit" },
            { "<leader>FR", desc = "Flutter Hot Reload" },
            { "<leader>FS", desc = "Flutter Hot Restart" },
            { "<leader>FD", desc = "Flutter Devices" },
            { "<leader>FE", desc = "Flutter Emulators" },
            { "<leader>Fo", desc = "Flutter Outline" },
            { "<leader>Fl", desc = "Flutter Dev Log" },
            { "<leader>Fc", desc = "Clear Flutter Log" },
            { "<leader>Fp", desc = "Flutter Pub Get" },
            { "<leader>Fa", desc = "Flutter Reanalyze" },
            { "<leader>FL", desc = "Restart Dart LSP" },
            { "og",         desc = "Toggle OpenCode Chat" },
            { "oo",         desc = "OpenCode Output" },
            { "o/",         desc = "Quick Buffer Chat",          mode = { "n", "x" } },
            { "]t",         desc = "Next Todo" },
            { "[t",         desc = "Previous Todo" },
            { "gr",         desc = "References" },
            { "gI",         desc = "Implementations" },
            { "gy",         desc = "Type Definition" },
            { "gai",        desc = "Incoming Calls" },
            { "gao",        desc = "Outgoing Calls" },
        })
    end,
}
